Controllers/AquariumWaterSituationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject.Models;
using System.Data.Entity;
using Newtonsoft.Json;
using System.Text;

namespace TestProject.Controllers
{
    public class AquariumWaterSituationController : Controller
    {
        private WaterQualityEntities1 db = new WaterQualityEntities1();
        // GET: AquariumSituation
        public ActionResult Index()
        {
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }
            string Email = Session["UserEmail"].ToString();
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            // 該使用者所擁有的所有魚缸
            List<Aquarium> TitleDataList = db.Aquarium.Where(x => x.Auth001Id == Auth001Id && x.BindTag == "0").ToList();
            List<AquariumSituation> DataList = new List<AquariumSituation>();

            //用來判斷按鈕是否可按的list
            List<int> ButtonJudge = new List<int>();

            for (int i = 0; i < TitleDataList.Count; i++)
            {
                //取得魚缸對應的AquaruimId
                int UnitUum = TitleDataList[i].Id;

                //將對應 AquaruimId 的數據全部抓出
                List<AquariumSituation> DataArray = db.AquariumSituation.Where(x => x.AquariumId == UnitUum).ToList();
                AquariumSituation DataGarge = new AquariumSituation();


                if (DataArray.Count == 0)
                {
                    ButtonJudge.Add(0);
                    DataGarge.temperature = "沒有紀錄";
                    DataGarge.Turbidity = "沒有紀錄";
                    DataGarge.PH = "沒有紀錄";
                    DataGarge.TDS = "沒有紀錄";
                    DataGarge.WaterLevel = "沒有紀錄";
                    DataList.Add(DataGarge);
                    continue;
                }

                //資料必須要大於等於6比，按鈕才能給按
                if (DataArray.Count > 0)
                {
                    // 為 1 代表有資料，所以提供圖表顯示
                    ButtonJudge.Add(1);
                }
                else
                {
                    // 為 0 代表不能按
                    ButtonJudge.Add(0);
                }

                DataGarge = DataArray[DataArray.Count - 1];
                DataList.Add(DataGarge);
            }
            ViewBag.ButtonJudge = ButtonJudge;
            ViewBag.DataList = DataList;
            ViewBag.TitleDataList = TitleDataList;
            return View();
        }

        /// <summary>
        /// 取得用戶對應魚缸編號的水質狀況
        /// </summary>
        public ActionResult PeriodQuality(string AquariumNum)
        {
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }
            string Email = Session["UserEmail"].ToString();
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            Aquarium AquariumData = db.Aquarium.FirstOrDefault(x => x.AquariumUnitNum == AquariumNum && x.BindTag == "0");

            //透過魚缸編號得知該魚缸目前跟使用者對應的AquariumId
            int AquariumIdNum = AquariumData.Id;
    
            // ALL DATA，把該魚缸代碼所有的資料全部丟到前端
            List<AquariumSituation> AllData = db.AquariumSituation.Where(x => x.AquariumId == AquariumIdNum)
                                                                  .OrderByDescending(x => x.createTime).ToList().ToList();
            // 不讓用戶知道魚缸代碼
            foreach (var data in AllData)
            {
                data.AquariumId = 0;
            }
            ViewBag.AllData = Newtonsoft.Json.JsonConvert.SerializeObject(AllData);

            // 資料長度
            ViewBag.AllDataCount = AllData.Count;
            ViewBag.AquariumNum = AquariumNum;
            ViewBag.AquariumData = AquariumData;
            return View();
        }
    }
}

Controllers/HistoryQueryController.cs
using Microsoft.AspNetCore.Cors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject.Models;

namespace TestProject.Controllers
{
    public class HistoryQueryController : Controller
    {
        private WaterQualityEntities1 db = new WaterQualityEntities1();
        // GET: HistoryQuery
        public ActionResult Index()
        {
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [EnableCors("Policy1")]
        public ActionResult GetUserData(string AquariumNum)
        {
            // 取得帳戶ID
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            // 先把所有對應魚缸編號的魚缸抓出
            List<Aquarium> Datalist = db.Aquarium.Where(x => x.AquariumUnitNum == AquariumNum).ToList();


            if (Datalist.Count == 0)
            {
                // 有可能用戶是輸入魚缸暱稱，因此將用戶的暱稱轉成AquariumNum 再找一次
                Aquarium CustomNameToAquariumNum = db.Aquarium.FirstOrDefault(x => x.Auth001Id == Auth001Id &&
                                                                          x.customAquaruimName == AquariumNum);
                if (CustomNameToAquariumNum != null)
                {
                    Datalist = db.Aquarium.Where(x => x.AquariumUnitNum == CustomNameToAquariumNum.AquariumUnitNum).ToList();
                }
                
            }

            List<string[]> data = new List<string[]>();
            for (int i = 0; i < Datalist.Count; i++)
            {
                string bindtag = "";
                if (Datalist[i].BindTag.Equals("1"))
                {
                    bindtag = "解綁";
                }
                else
                {
                    bindtag = "使用中";
                }
                string[] item = new string[] { Datalist[i].createTime.ToString(),
                                                Datalist[i].modifyTime.ToString(),
                                                bindtag };
                data.Add(item);
            }
            return Json(data, "text/json", JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/NotifyByMailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using TestProject.Models.MailTest;
using TestProject.Models;

//必須多添加這using 才能使用Entity Framework的Save功能
using System.Data.Entity;

using System.Net;
using System.Collections.Specialized;
using System.Text;
using Newtonsoft.Json.Linq;


namespace TestProject.Controllers
{
    public class NotifyByMailController : Controller
    {
        private WaterQualityEntities1 db = new WaterQualityEntities1();
        public ActionResult SetAreaRange()
        {
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }
            string Email = Session["UserEmail"].ToString();
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            // 該使用者所擁有的所有魚缸
            List<Aquarium> TitleDataList = db.Aquarium.Where(x => x.Auth001Id == Auth001Id && x.BindTag == "0").ToList();
            int TitleDataListSize = TitleDataList.Count;
            string[] TitleDataListNotifyOnOrOff = new string[TitleDataListSize];

            //將有開啟通知的魚缸全抓出來
            for (int i = 0; i < TitleDataListSize; i++)
            {
                string AquariumNum = TitleDataList[i].AquariumUnitNum;
                NotifySetRange NotifyOnListData = db.NotifySetRange.FirstOrDefault(x => x.AquariumUnitNum == AquariumNum);
                if (NotifyOnListData != null)
                {
                    //代表這筆有開啟通知
                    if (NotifyOnListData.NotifyTag == "1")
                    {
                        TitleDataListNotifyOnOrOff[i] = "開啟";
                    }
                    if (NotifyOnListData.NotifyTag == "0")
                    {
                        TitleDataListNotifyOnOrOff[i] = "關閉";
                    }

                }
                else
                {
                    //代表這筆未開啟通知
                    TitleDataListNotifyOnOrOff[i] = "未定";
                }
            }
            ViewBag.TitleDataListNotifyOnOrOff = TitleDataListNotifyOnOrOff;
            ViewBag.AquariumDataList = TitleDataList;

            if (base.TempData["SuccessState"] != null)
            {
                Auth001 UserInfo = new Auth001();

                return View(UserInfo);
            }

            return View();
        }

        public ActionResult SetAreaRangeCheck(string AquariumNum)
        {
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }
            string Email = Session["UserEmail"].ToString();
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            //核對開鹿由參數是否是該使用者的
            Aquarium DataCheck = db.Aquarium.FirstOrDefault(x => x.Auth001Id == Auth001Id && x.AquariumUnitNum == AquariumNum && x.BindTag == "0");
            //若不是該使用者就反回首頁
            if (DataCheck == null)
            {
                return RedirectToAction("Index", "Home");
            }
            NotifySetRange DataTarget = db.NotifySetRange.FirstOrDefault(x => x.AquariumUnitNum == AquariumNum);
            if (DataTarget == null)
            {
                //若資料庫沒有該區間設定，就先初始化該魚缸的區間設定
                DataTarget = new NotifySetRange();
                DataTarget.AquariumUnitNum = AquariumNum;
                DataTarget.temperatureUpperBound = "100";
                DataTarget.temperatureLowerBound = "0";
                DataTarget.pHUpperBound = "14";
                DataTarget.phLowerBound = "0";
                DataTarget.TDSUpperBound = "10000";
                DataTarget.TDSLowerBound = "0";
                DataTarget.TurbidityUpperBound = "3000";
                DataTarget.WaterLevelLowerBound = "1";
                DataTarget.NotifyTag = "0";

            }
            //若資料庫有該該區間設定，就直接送到前端
            ViewBag.DataTarget = DataTarget;
            ViewBag.AquarinmNum = AquariumNum;
            return View();
        }
        [HttpPost]
        public ActionResult GetUserRangeData(NotifySetRange DataTarget)
        {
            // 時間到時請用戶重新登入
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }
            // 得知操作的用戶對象
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            // 得知目前設定的魚缸編號
            string AquariumTargerNum = DataTarget.AquariumUnitNum;
            // 取得用戶設定的魚缸狀態
            string NotifyTag = DataTarget.NotifyTag;

            // 取得當前魚缸唯一碼所綁定的魚缸Id為多少
            Aquarium DataCheck = db.Aquarium.FirstOrDefault(x => x.Auth001Id == Auth001Id && x.AquariumUnitNum == AquariumTargerNum && x.BindTag == "0");

            double temperatureUpperBound,
                temperatureLowerBound,
                pHUpperBound,
                phLowerBound,
                TDSUpperBound,
                TDSLowerBound,
                TurbidityUpperBound,
                WaterLevelLowerBound;

            // 確定傳過來的都為福點數後
            if (double.TryParse(DataTarget.temperatureUpperBound, out temperatureUpperBound) &&
                double.TryParse(DataTarget.temperatureLowerBound, out temperatureLowerBound) &&
                double.TryParse(DataTarget.pHUpperBound, out pHUpperBound) &&
                double.TryParse(DataTarget.phLowerBound, out phLowerBound) &&
                double.TryParse(DataTarget.TDSUpperBound, out TDSUpperBound) &&
                double.TryParse(DataTarget.TDSLowerBound, out TDSLowerBound) &&
                double.TryParse(DataTarget.TurbidityUpperBound, out TurbidityUpperBound) &&
                double.TryParse(DataTarget.WaterLevelLowerBound, out WaterLevelLowerBound) &&
                DataCheck != null)
            {
                //成功
                NotifySetRange UpdateTarget = db.NotifySetRange.FirstOrDefault(x => x.AquariumUnitNum == AquariumTargerNum);

                //看資料庫是否有該魚缸編號的紀錄
                if (UpdateTarget == null)
                {
                    // 目前Table沒有該魚缸資料
                    UpdateTarget = new NotifySetRange();
                    UpdateTarget.AquariumUnitNum = AquariumTargerNum;
                    UpdateTarget.AquariumId = DataCheck.Id;
                    UpdateTarget.temperatureUpperBound = temperatureUpperBound.ToString();
                    UpdateTarget.temperatureLowerBound = temperatureLowerBound.ToString();
                    UpdateTarget.pHUpperBound = pHUpperBound.ToString();
                    UpdateTarget.phLowerBound = phLowerBound.ToString();
                    UpdateTarget.TDSUpperBound = TDSUpperBound.ToString();
                    UpdateTarget.TDSLowerBound = TDSLowerBound.ToString();
                    UpdateTarget.TurbidityUpperBound = TurbidityUpperBound.ToString();
                    UpdateTarget.WaterLevelLowerBound = WaterLevelLowerBound.ToString();
                    UpdateTarget.NotifyTag = NotifyTag;

                    db.NotifySetRange.Add(UpdateTarget);
                    db.SaveChanges();
                }
                else
                {
                    // 目前Table有該魚缸資料
                    UpdateTarget.temperatureUpperBound = temperatureUpperBound.ToString();
                    UpdateTarget.temperatureLowerBound = temperatureLowerBound.ToString();
                    UpdateTarget.pHUpperBound = pHUpperBound.ToString();
                    UpdateTarget.phLowerBound = phLowerBound.ToString();
                    UpdateTarget.TDSUpperBound = TDSUpperBound.ToString();
                    UpdateTarget.TDSLowerBound = TDSLowerBound.ToString();
                    UpdateTarget.TurbidityUpperBound = TurbidityUpperBound.ToString();
                    UpdateTarget.WaterLevelLowerBound = WaterLevelLowerBound.ToString();
                    UpdateTarget.NotifyTag = NotifyTag;

                    db.Entry(UpdateTarget).State = EntityState.Modified;
                    db.SaveChanges();
                }
                base.TempData["SuccessState"] = string.Format("編號:{0} 設定完成!", AquariumTargerNum);

                return RedirectToAction("SetAreaRange");

            }
            else
            {
                //失敗
                return Redirect("Error");
            }

        }

        public ActionResult GetCodePlace(string code, string state)
        {
            if (Session["UserEmail"] == null)
            {
                Session.RemoveAll();
                return RedirectToAction("Index", "Home");
            }

            var wb = new WebClient();
            var data = new NameValueCollection();

            string url = "https://notify-bot.line.me/oauth/token";
            data["grant_type"] = "authorization_code";
            data["code"] = code.ToString();
            data["redirect_uri"] = "http://192.168.0.80:52809/NotifyByMail/GetCodePlace";
            data["client_id"] = "uhkcosVjss3RuzULJ4uNIz";
            data["client_secret"] = "Hrp2nTtXeEIHw574e5pVldKEODre6t9gHwiwlIu1arO";

            // 送出資料
            var response = wb.UploadValues(url, "POST", data);
            // 取得回傳值
            string str = Encoding.UTF8.GetString(response);

            // 將回傳字串json轉為Dictionary
            Dictionary<string, string> UserDataHaveToken = ToDictionary(str);
            // 取出字典的 access_token，這是用戶對應的Token
            string UserToken = UserDataHaveToken["access_token"];

            string Email = Session["UserEmail"].ToString();
            int Auth001Id = int.Parse(Session["Auth001Id"].ToString());

            Auth001 auth001 = db.Auth001.FirstOrDefault(x => x.Id == Auth001Id);


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>魚缸水質監控網</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/sweetalert.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
</head>



<style>

    @@media only screen and (max-width:1200px) {
        .D1 {
            display: none;
        }

        .D2 {
            display: block;
        }
    }

    @@media only screen and (min-width:1200px) {
        .D1 {
            display: block;
        }

        .D2 {
            display: none;
        }
    }

    .navbar-inverse .navbar-toggle {
        background-color: #286090;
    }

    .navbar-toggle {
        background-color: #286090;
        margin-top: 5%;
    }

    .navbar-inverse .navbar-toggle:hover, .navbar-inverse .navbar-toggle:focus {
        background-color: #283990;
    }
</style>



<body>
    <div class="D1">
        <div class="navbar navbar-inverse navbar-fixed-top" style="border-color:#dae8fc ">
            <div class="container">
                <div class="navbar-header" style="padding-top: 10px;">
                    <button type="button" class="navbar-toggle collapse " navbar-collapse collapse" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("魚缸水質監控網", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse" style="height:110px !important;padding-top:35px;">
                    <ul class="nav navbar-nav navbar-right" style="position: relative; bottom: 0px; right: 0px;">
                        @*<li><a href="http://tlc.sainter.com.tw/">線上提報系統</a></li>*@
                        @{
                            if (Session["UserEmail"] == null)
                            {
                                <li>@Html.ActionLink("公告與說明", "About", "Home")</li>
                                <li>@Html.ActionLink("用戶介面", "CreateOrLogIn", "LogInAndRegister")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("通報設置", "SetAreaRange", "NotifyByMail")</li>
                                <li>@Html.ActionLink("綁定紀錄查詢", "Index", "HistoryQuery")</li>
                                <li>@Html.ActionLink("編輯與綁定", "Bind", "BindAquarium")</li>
                                <li>@Html.ActionLink("水質狀況", "Index", "AquariumWaterSituation")</li>
                                <li>@Html.ActionLink("公告與說明", "About", "Home")</li>
                                <li>@Html.ActionLink("登出", "LogOut", "LogInAndRegister")</li>
                            }
                        }

                    </ul>
                </div>
                <div class="bg-pic">
                </div>
            </div>
        </div>
    </div>
    <div class="D2">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="其他選項">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("魚缸水質監控網", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        @{
                            if (Session["UserEmail"] == null)
                            {
                                <li>@Html.ActionLink("公告與說明", "About", "Home")</li>
                                <li>@Html.ActionLink("登入 / 註冊", "CreateOrLogIn", "LogInAndRegister")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("通報設置", "SetAreaRange", "NotifyByMail")</li>
                                <li>@Html.ActionLink("綁定紀錄查詢", "Index", "HistoryQuery")</li>
                                <li>@Html.ActionLink("編輯與綁定", "Bind", "BindAquarium")</li>
                                <li>@Html.ActionLink("水質狀況", "Index", "AquariumWaterSituation")</li>
                                <li>@Html.ActionLink("公告與說明", "About", "Home")</li>
                                <li>@Html.ActionLink("登出", "LogOut", "LogInAndRegister")</li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:100px">
        @RenderBody()

        @*<footer>
                <div style="color: #000; text-align: center; background-color: #dae8fc; height: 10vh; max-width: 100%; display: flex; align-items: center; justify-content: center ">
                    <p style="margin-bottom:0px;font-size:15px">
                        &copy; @DateTime.Now.Year - 網站維護：技專校院總量管制小組
                    </p>
                </div>
            </footer>*@
    </div>
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<style>

    .navbar-brand2 {
        background: url(/Content/web_02_new.png) no-repeat center left;
        background-size: contain;
        display: block;
        width: 675px;
        height: 110px;
        text-indent: -9999px;
    }

    .navbar {
        background-color: #dae8fc;
        min-height: 120px;
    }

    .view_total > div > input {
        background-color: #5A7C7C;
        font-size: large;
        height: 50px;
        width: 90%;
        margin: 10px;
    }

    ul {
        padding: 0px;
    }

    /*.navbar-inverse .navbar-nav > li > a {
        color: white;
        transition: box-shadow 0.3s, transform 0.4s,color 0.2s;
    }

        .navbar-inverse .navbar-nav > li > a:hover,
        .navbar_inverse .navbar-nav > li > a:focus {
            color: #5050F7;
            box-shadow: 3px 3px 9px #5050F7;
            background-color: #9b8cff;
            transform: translateY(-2px) rotate(1deg);
            cursor: default;
        }*/

    /*選單STYLE設定*/
    .navbar-inverse .navbar-nav > li > a {
        font-size: 20px;
        color: blue;
        font-weight: bold;
    }

        .navbar-inverse .navbar-nav > li > a:hover,
        .navbar-inverse .navbar-nav > li > a:focus {
            color: green;
        }
    /*標題STYLE設定*/
    .navbar-inverse .navbar-brand {
        font-size: 37px;
        color: black;
        font-weight: bold;
    }

        .navbar-inverse .navbar-brand:hover,
        .navbar-inverse .navbar-brand:focus {
            color: blue;
        }

    .navbar-inverse .navbar-nav > li > a {
        color: blue;
        transition: box-shadow 0.3s, transform 0.4s,color 0.3s;
    }

        .navbar-inverse .navbar-nav > li > a:hover,
        .navbar-inverse .navbar-nav > li > a:focus {
            color: blue;
            box-shadow: 3px 3px 9px #5050F7;
            background-color: rgb(218, 255, 252);
            transform: translateY(-2px);
            cursor: default;
        }

    /*.navbar-inverse .navbar-nav > .open > a {
        color: white;
        transition: box-shadow 0.3s, transform 0.4s,color 0.2s;
    }

        .navbar-inverse .navbar-nav > .open > a:hover,
        .navbar-inverse .navbar-nav > .open > a:focus {
            color: #5050F7;
            box-shadow: 3px 3px 9px #5050F7;
            background-color: #9b8cff;
            transform: translateY(-2px) rotate(1deg);
        }*/
    .dropdown-menu li:hover .sub-menu {
        visibility: visible;
    }

    .dropdown:hover .dropdown-menu {
        display: block;
    }
</style>